#baseURL = 'latentpng.com'
languageCode = 'en-us'
title = 'ONESTEPMUMU'
theme = "paper"

#disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'MumuOneste33579'               # twitter.com/YOUR_TWITTER_ID
  github = 'onestepmumu'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  # home page profile
  #avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  #name = 'onestepmumu'
  #bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # giscus
#[params.giscus]
#  repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
#  repoId = 'YOUR_GISCUS_REPO_ID'
#  category = 'YOUR__GISCUS_CATEGORY'
#  categoryId = 'YOUR_GISCUS_CATEGORY_ID'
#  mapping = 'pathname'
#  theme = 'light'
#  lang = 'zh-CN'

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4


